/**
 * Order Model
 * Manages emergency fuel delivery orders
 */

const mongoose = require('mongoose');
const { ORDER_STATUS, FUEL_TYPES } = require('../config/constants');

const orderSchema = new mongoose.Schema({
  // Order Number (unique identifier)
  orderNumber: {
    type: String,
    // ✅ FIXED: Not required on creation (auto-generated in pre-save)
    required: false,
    unique: true,
    sparse: true, // Allow null values temporarily before generation
    trim: true
  },
  
  // Customer Information
  customer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  
  // Delivery Partner
  deliveryPartner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  
  // Petrol Bunk
  petrolBunk: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'PetrolBunk',
    // ✅ FIXED: Made optional for emergency orders
    required: false,
    default: null
  },
  
  // Order Status
  status: {
    type: String,
    enum: Object.values(ORDER_STATUS),
    default: ORDER_STATUS.PENDING,
    required: true
  },
  
  // Fuel Details
  fuelDetails: {
    type: {
      type: String,
      enum: Object.values(FUEL_TYPES),
      required: true
    },
    quantity: {
      type: Number,
      required: true,
      min: [0.5, 'Minimum quantity is 0.5 liters'],
      max: [5, 'Maximum quantity is 5 liters for safety']
    },
    pricePerLiter: {
      type: Number,
      required: true,
      min: 0
    },
    totalFuelCost: {
      type: Number,
      required: true,
      min: 0
    }
  },
  
  // Delivery Location
  deliveryLocation: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true
    },
    address: {
      type: String,
      required: false, // ✅ FIXED: Made optional since it might be empty
      default: ''
    },
    landmark: String
  },
  
  // Distance
  distance: {
    toCustomer: {
      type: Number, // in km
      required: true,
      min: 0
    }
  },
  
  // Charges
  charges: {
    fuelCost: {
      type: Number,
      required: true,
      min: 0
    },
    deliveryCharge: {
      type: Number,
      required: true,
      min: 0
    },
    emergencyFee: {
      type: Number,
      required: true,
      default: 50
    },
    totalAmount: {
      type: Number,
      required: true,
      min: 0
    }
  },
  
  // OTP for delivery verification
  deliveryOtp: {
    code: {
      type: String,
      // ✅ FIXED: Not required on creation (generated by method)
      required: false,
      length: 6
    },
    verified: {
      type: Boolean,
      default: false
    },
    verifiedAt: Date
  },
  
  // Timeline
  timeline: [{
    status: {
      type: String,
      enum: Object.values(ORDER_STATUS)
    },
    timestamp: {
      type: Date,
      default: Date.now
    },
    notes: String
  }],
  
  // Times
  estimatedDeliveryTime: Date,
  actualDeliveryTime: Date,
  partnerAssignedAt: Date,
  pickedUpAt: Date,
  deliveredAt: Date,
  
  // Cancellation
  cancellation: {
    cancelledBy: {
      type: String,
      enum: ['customer', 'partner', 'bunk', 'admin']
    },
    reason: String,
    cancelledAt: Date
  },
  
  // Safety Acknowledgment
  safetyAcknowledged: {
    type: Boolean,
    required: true,
    default: false
  }

}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
orderSchema.index({ orderNumber: 1 });
orderSchema.index({ customer: 1, createdAt: -1 });
orderSchema.index({ deliveryPartner: 1, status: 1 });
orderSchema.index({ petrolBunk: 1, status: 1 });
orderSchema.index({ status: 1 });
orderSchema.index({ deliveryLocation: '2dsphere' });

// ✅ FIXED: Pre-save - Generate order number BEFORE validation
orderSchema.pre('validate', async function(next) {
  if (this.isNew && !this.orderNumber) {
    const date = new Date();
    const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
    const randomStr = Math.random().toString(36).substring(2, 8).toUpperCase();
    this.orderNumber = `PG${dateStr}${randomStr}`;
  }
  next();
});

// Pre-save: Add timeline entry
orderSchema.pre('save', function(next) {
  if (this.isModified('status')) {
    this.timeline.push({
      status: this.status,
      timestamp: new Date()
    });
  }
  next();
});

// Generate delivery OTP
orderSchema.methods.generateDeliveryOtp = function() {
  const otp = Math.floor(100000 + Math.random() * 900000).toString();
  this.deliveryOtp.code = otp;
  return otp;
};

// Verify delivery OTP
orderSchema.methods.verifyDeliveryOtp = function(otp) {
  if (this.deliveryOtp.code === otp) {
    this.deliveryOtp.verified = true;
    this.deliveryOtp.verifiedAt = new Date();
    return true;
  }
  return false;
};

// Calculate total amount
orderSchema.methods.calculateTotalAmount = function() {
  const { fuelCost, deliveryCharge, emergencyFee } = this.charges;
  const total = fuelCost + deliveryCharge + emergencyFee;
  this.charges.totalAmount = Math.round(total * 100) / 100;
  return this.charges.totalAmount;
};

const Order = mongoose.model('Order', orderSchema);

module.exports = Order;